# Generated by Django 5.2.5 on 2025-09-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_doctor_pacient_user_type_alter_pacient_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.medico'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
