services:
  app: 
    container_name: web
    build: .
    command: bash -c "./prestart.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - web-network

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web-network

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - web-network

volumes:
  postgres_data:

networks:
  web-network:  
    driver: bridge
